name: Master Link Check and Multi-NIC test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 06 * * *" # run at 12:00 PM IST

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt
      - uses: coursier/cache-action@v6
      - run: sudo chmod 666 /var/run/docker.sock

      - name: Package
        run: ./integration/scripts/bootstrap_standalone_jars.sh

      - name: Multi-NICs Docker
        run: ./integration/scripts/multiple_nic_test.sh

      - name: Paradox Validate Links
        run: sbt docs/paradoxValidateLinks

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-linkcheck
